### PR TITLE
Added support for embedding tiddlywiki in the binary

### PR DESCRIPTION
**Pull request by roelrymenants**
Possible open ends:
- Allow serving from a local file again with a flag
- Address licensing issue for tiddlywiki

As requested in #1

### CODE REVIEW

**Comment by roelrymenants** [comment]
@ay-wowed: how do we address the licensing? Just add a reference in the readme? Include their license file next to ours? Next to the file?

Also: it's a pity we have to include the actual html file in git, but we need an extra plugin (so we can't just download the empty.html from the tiddlywiki website). Possibly the nodejs tiddlywiki app supports generating it including a plugin, but that seemed like a lot of work (and certainly wouldn't make the build process any easier).

**Comment by ay-wowed** [comment]
Actually, the license is included in every copy of TiddlyWiki in the "$:/core/copyright.txt" Tiddler.

**Comment by roelrymenants** [comment]
So we should be good with the addition to the readme and the reproduction of the copyright and license as required by the license?

**Comment by ay-wowed** [comment]
IANAL, but I believe so.

**Pull request merged**
